version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "kilogram"
      POSTGRES_USER: "kilogram"
      POSTGRES_PASSWORD: "kilogram"
    ports:
      - "3000:5432"
