version: "3.9"
services:
  postgres:
    image: postgres:13.3
    env_file:
      - env/db.env
    ports:
      - "5432:5432"
    networks:
      - database_bridge

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command:
      - redis-server --requirepass kilogram323
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    env_file:
      - env/client.env
    networks:
      - client_bridge
    ports:
      - "3001:80"

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file:
      - env/server.env
    networks:
      - database_bridge
      - server_bridge
    ports:
      - "3002:3002"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    networks:
      - client_bridge
      - server_bridge
    depends_on:
      - client
      - server

networks:
  client_bridge:
    driver: bridge

  server_bridge:
    driver: bridge

  database_bridge:
    driver: bridge
