version: "3.9"
services:
  postgres:
    image: postgres:13.3
    env_file:
      - env/db.env
    ports:
      - "5432:5432"
    networks:
      - database_bridge

  client:
    image: kilogram/client
    build:
      context: .
      dockerfile: client.Dockerfile
    env_file:
      - env/client.env
    networks:
      - client_bridge
    ports:
      - "3001:80"

  server:
    image: kilogram/server
    build:
      context: .
      dockerfile: server.Dockerfile
    volumes:
      - /app/node_modules
    env_file:
      - env/server.env
    networks:
      - database_bridge
      - server_bridge
    ports:
      - "3002:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    networks:
      - client_bridge
      - server_bridge
    depends_on:
      - client
      - server

networks:
  client_bridge:
    driver: bridge

  server_bridge:
    driver: bridge

  database_bridge:
    driver: bridge
